#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#runApplication blockMesh
#runApplication picInitialise
#runApplication $(getApplication)

runApplication blockMesh
runApplication decomposePar
runParallel picInitialise
runParallel $(getApplication)
runApplication reconstructPar #-noLagrangian


#------------------------------------------------------------------------------
