/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     | Website:  https://openfoam.org
    \\  /    A nd           | Copyright (C) 2011-2019 OpenFOAM Foundation
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

Class
    Foam::PICBaseCloud

Description
    Virtual abstract base class for templated PICCloud

SourceFiles
    PICBaseCloud.C

\*---------------------------------------------------------------------------*/

#ifndef PICBaseCloud_H
#define PICBaseCloud_H

#include "volFields.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
                       Class PICBaseCloud Declaration
\*---------------------------------------------------------------------------*/

class PICBaseCloud
{
public:

    //- Runtime type information
    TypeName("PICBaseCloud");

    // Constructors

        //- Null constructor
        PICBaseCloud();

        //- Disallow default bitwise copy construction
        PICBaseCloud(const PICBaseCloud&) = delete;


    //- Destructor
    virtual ~PICBaseCloud();


    // Member Operators

        //- Disallow default bitwise assignment
        void operator=(const PICBaseCloud&) = delete;
};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
